### ISSUE TITLE
Development boards/arduino images cannot be displayed

### ISSUE THREAD

**Issue by enceladus2000** [ERC-BPGC/handbook#28]
https://erc-bpgc.github.io/handbook/electronics/Development_Boards/Arduino/ pictures aren't visible

**Comment by veds12** [comment]
Solved. Looks like HTML tags in md files don't work for mkdocs

**Comment by enceladus2000** [comment]
I used <img> tags so that i could resize the images, but mkdocs gave bt. So instead one can use attr_list as shown here https://github.com/mkdocs/mkdocs/issues/1678
